
/*  © Copyright CERN, 2015. All rights not expressly granted are reserved.

    The stub of this file was generated by quasar (https://github.com/quasar-team/quasar/)

    Quasar is free software: you can redistribute it and/or modify
    it under the terms of the GNU Lesser General Public Licence as published by
    the Free Software Foundation, either version 3 of the Licence.
    Quasar is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Lesser General Public Licence for more details.

    You should have received a copy of the GNU Lesser General Public License
    along with Quasar.  If not, see <http://www.gnu.org/licenses/>.


 */


#ifndef __DFEMBPower__H__
#define __DFEMBPower__H__

#include <Base_DFEMBPower.h>

namespace Device
{

class
    DFEMBPower
    : public Base_DFEMBPower
{

public:
    /* sample constructor */
    explicit DFEMBPower (
        const Configuration::FEMBPower& config,
        Parent_DFEMBPower* parent
    ) ;
    /* sample dtr */
    ~DFEMBPower ();

    /* delegators for
    cachevariables and sourcevariables */


    /* delegators for methods */
    UaStatus callSet (
        OpcUa_Boolean femb0_on,
        OpcUa_Boolean femb1_on,
        OpcUa_Boolean femb2_on,
        OpcUa_Boolean femb3_on,
        OpcUa_Boolean cold,
        OpcUa_UInt32 stage,
        OpcUa_Boolean& success
    ) ;

private:
    /* Delete copy constructor and assignment operator */
    DFEMBPower( const DFEMBPower& other );
    DFEMBPower& operator=(const DFEMBPower& other);

    // ----------------------------------------------------------------------- *
    // -     CUSTOM CODE STARTS BELOW THIS COMMENT.                            *
    // -     Don't change this comment, otherwise merge tool may be troubled.  *
    // ----------------------------------------------------------------------- *

public:

private:



};

}

#endif // __DFEMBPower__H__