
/*  © Copyright CERN, 2015. All rights not expressly granted are reserved.

    The stub of this file was generated by quasar (https://github.com/quasar-team/quasar/)

    Quasar is free software: you can redistribute it and/or modify
    it under the terms of the GNU Lesser General Public Licence as published by
    the Free Software Foundation, either version 3 of the Licence.
    Quasar is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Lesser General Public Licence for more details.

    You should have received a copy of the GNU Lesser General Public License
    along with Quasar.  If not, see <http://www.gnu.org/licenses/>.


 */


#ifndef __DWIB__H__
#define __DWIB__H__

#include <Base_DWIB.h>

namespace Device
{

class
    DWIB
    : public Base_DWIB
{

public:
    /* sample constructor */
    explicit DWIB (
        const Configuration::WIB& config,
        Parent_DWIB* parent
    ) ;
    /* sample dtr */
    ~DWIB ();

    /* delegators for
    cachevariables and sourcevariables */


    /* delegators for methods */
    UaStatus callGetFWVersion (
        OpcUa_UInt32& version
    ) ;
    UaStatus callGetSWVersion (
        UaString& version
    ) ;

private:
    /* Delete copy constructor and assignment operator */
    DWIB( const DWIB& other );
    DWIB& operator=(const DWIB& other);

    // ----------------------------------------------------------------------- *
    // -     CUSTOM CODE STARTS BELOW THIS COMMENT.                            *
    // -     Don't change this comment, otherwise merge tool may be troubled.  *
    // ----------------------------------------------------------------------- *

public:

private:



};

}

#endif // __DWIB__H__